# Generated by Django 4.1.3 on 2022-11-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество тортов')),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='bot.cake', verbose_name='торты')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='bot.order', verbose_name='заказы')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cakes',
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(related_name='orders', through='bot.OrderedCake', to='bot.cake', verbose_name='торты'),
        ),
    ]
